CREATE TABLE EBX_RRO (
	id NUMBER(10) NOT NULL ,
	mode_key NVARCHAR2(50) NOT NULL ,
	heart_beat_interval NUMBER(10) NOT NULL ,
	host_name NVARCHAR2(300),
	host_address NVARCHAR2(300),
	product_version NVARCHAR2(50) NOT NULL ,
	insert_time TIMESTAMP NOT NULL ,
	state NVARCHAR2(1) NOT NULL ,
	rro_flag NUMBER(10) NOT NULL ,
	rro_request_time TIMESTAMP,
	rro_hold_time TIMESTAMP,
	heart_beat_time TIMESTAMP,
	heart_beat_count NUMBER(10),
	heart_beat_max_interval NUMBER(10),
	pre_commit_count NUMBER(10),
	post_commit_count NUMBER(10),
	marked_dead_time TIMESTAMP,
	marked_dead_origin NUMBER(10),
	system_info CLOB,
	CONSTRAINT EBX_RRO_PK PRIMARY KEY  (id),
	CONSTRAINT EBX_RRO_UNQ UNIQUE  (rro_flag));
