CREATE TABLE EBX_RRO (
	id INTEGER NOT NULL ,
	mode_key VARCHAR(50) NOT NULL ,
	heart_beat_interval INTEGER NOT NULL ,
	host_name VARCHAR(300),
	host_address VARCHAR(300),
	product_version VARCHAR(50) NOT NULL ,
	insert_time TIMESTAMP NOT NULL ,
	state VARCHAR(1) NOT NULL ,
	rro_flag INTEGER NOT NULL ,
	rro_request_time TIMESTAMP,
	rro_hold_time TIMESTAMP,
	heart_beat_time TIMESTAMP,
	heart_beat_count INTEGER,
	heart_beat_max_interval INTEGER,
	pre_commit_count INTEGER,
	post_commit_count INTEGER,
	marked_dead_time TIMESTAMP,
	marked_dead_origin INTEGER,
	system_info TEXT,
	CONSTRAINT EBX_RRO_PK PRIMARY KEY  (id),
	CONSTRAINT EBX_RRO_UNQ UNIQUE  (rro_flag));
