CREATE TABLE EBX_HV_TX (
	tx_id INTEGER NOT NULL ,
	user_id INTEGER,
	action_id INTEGER,
	home_id INTEGER,
	session_id INTEGER,
	timestamp BIGINT,
	uuid VARCHAR(36),
	execution_info VARCHAR(10485760),
	CONSTRAINT EBX_HV_TX_PK PRIMARY KEY  (tx_id));
CREATE SEQUENCE EBX_HV_TX_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_TX_STAT (
	tx_id INTEGER NOT NULL ,
	instance_id INTEGER,
	txs INTEGER,
	nb_creates INTEGER,
	nb_updates INTEGER,
	nb_deletes INTEGER);
CREATE SEQUENCE EBX_HV_TX_STAT_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_USER (
	user_id INTEGER NOT NULL ,
	name VARCHAR(10485760),
	CONSTRAINT EBX_HV_USER_PK PRIMARY KEY  (user_id));
CREATE SEQUENCE EBX_HV_USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_ACTION (
	action_id INTEGER NOT NULL ,
	built_in_action_name VARCHAR(50),
	procedure_name VARCHAR(10485760),
	CONSTRAINT EBX_HV_ACTION_PK PRIMARY KEY  (action_id));
CREATE SEQUENCE EBX_HV_ACTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_INSTANCE (
	instance_id INTEGER NOT NULL ,
	reference VARCHAR(64),
	content_type VARCHAR(1),
	CONSTRAINT EBX_HV_INSTANCE_PK PRIMARY KEY  (instance_id));
CREATE SEQUENCE EBX_HV_INSTANCE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_HOM (
	home_id INTEGER NOT NULL ,
	home_name VARCHAR(32),
	home_type VARCHAR(1),
	CONSTRAINT EBX_HV_HOM_PK PRIMARY KEY  (home_id));
CREATE SEQUENCE EBX_HV_HOM_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_SESSION (
	session_id INTEGER NOT NULL ,
	session_type VARCHAR(512),
	ip_address VARCHAR(39),
	http_id VARCHAR(10485760),
	tracking_info VARCHAR(10485760),
	CONSTRAINT EBX_HV_SESSION_PK PRIMARY KEY  (session_id));
CREATE SEQUENCE EBX_HV_SESSION_SEQ START WITH 1 INCREMENT BY 1;
