CREATE TABLE EBX_HV_TX (
	tx_id INT NOT NULL ,
	user_id INT,
	action_id INT,
	home_id INT,
	session_id INT,
	timestamp NUMBER,
	uuid NVARCHAR2(36),
	execution_info NVARCHAR2(2147483647),
	CONSTRAINT EBX_HV_TX_PK PRIMARY KEY  (tx_id));
CREATE SEQUENCE EBX_HV_TX_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_TX_STAT (
	tx_id INT NOT NULL ,
	instance_id INT,
	txs INT,
	nb_creates INT,
	nb_updates INT,
	nb_deletes INT);
CREATE SEQUENCE EBX_HV_TX_STAT_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_USER (
	user_id INT NOT NULL ,
	name NVARCHAR2(2147483647),
	CONSTRAINT EBX_HV_USER_PK PRIMARY KEY  (user_id));
CREATE SEQUENCE EBX_HV_USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_ACTION (
	action_id INT NOT NULL ,
	built_in_action_name NVARCHAR2(50),
	procedure_name NVARCHAR2(2147483647),
	CONSTRAINT EBX_HV_ACTION_PK PRIMARY KEY  (action_id));
CREATE SEQUENCE EBX_HV_ACTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_INSTANCE (
	instance_id INT NOT NULL ,
	reference NVARCHAR2(64),
	content_type NVARCHAR2(1),
	CONSTRAINT EBX_HV_INSTANCE_PK PRIMARY KEY  (instance_id));
CREATE SEQUENCE EBX_HV_INSTANCE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_HOM (
	home_id INT NOT NULL ,
	home_name NVARCHAR2(32),
	home_type NVARCHAR2(1),
	CONSTRAINT EBX_HV_HOM_PK PRIMARY KEY  (home_id));
CREATE SEQUENCE EBX_HV_HOM_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE EBX_HV_SESSION (
	session_id INT NOT NULL ,
	session_type NVARCHAR2(512),
	ip_address NVARCHAR2(39),
	http_id NVARCHAR2(2147483647),
	tracking_info NVARCHAR2(2147483647),
	CONSTRAINT EBX_HV_SESSION_PK PRIMARY KEY  (session_id));
CREATE SEQUENCE EBX_HV_SESSION_SEQ START WITH 1 INCREMENT BY 1;
