CREATE TABLE EBX_RRO (
	id INTEGER NOT NULL ,
	mode_key NVARCHAR(50) NOT NULL ,
	heart_beat_interval INTEGER NOT NULL ,
	host_name NVARCHAR(300),
	host_address NVARCHAR(300),
	product_version NVARCHAR(50) NOT NULL ,
	insert_time DATETIME2 NOT NULL ,
	state NVARCHAR(1) NOT NULL ,
	rro_flag INTEGER NOT NULL ,
	rro_request_time DATETIME2,
	rro_hold_time DATETIME2,
	heart_beat_time DATETIME2,
	heart_beat_count INTEGER,
	heart_beat_max_interval INTEGER,
	pre_commit_count INTEGER,
	post_commit_count INTEGER,
	marked_dead_time DATETIME2,
	marked_dead_origin INTEGER,
	system_info NVARCHAR(MAX),
	CONSTRAINT EBX_RRO_PK PRIMARY KEY  (id),
	CONSTRAINT EBX_RRO_UNQ UNIQUE  (rro_flag));
