CREATE TABLE EBX_RRO (
	id INT NOT NULL ,
	mode_key NVARCHAR2(50) NOT NULL ,
	heart_beat_interval INT NOT NULL ,
	host_name NVARCHAR2(300),
	host_address NVARCHAR2(300),
	product_version NVARCHAR2(50) NOT NULL ,
	insert_time TIMESTAMP NOT NULL ,
	state NVARCHAR2(1) NOT NULL ,
	rro_flag INT NOT NULL ,
	rro_request_time TIMESTAMP,
	rro_hold_time TIMESTAMP,
	heart_beat_time TIMESTAMP,
	heart_beat_count INT,
	heart_beat_max_interval INT,
	pre_commit_count INT,
	post_commit_count INT,
	marked_dead_time TIMESTAMP,
	marked_dead_origin INT,
	system_info VARCHAR,
	CONSTRAINT EBX_RRO_PK PRIMARY KEY  (id),
	CONSTRAINT EBX_RRO_UNQ UNIQUE  (rro_flag));
