package com.orchestranetworks.geomatch;

//From what i can tell, this class just directs the java to look in the right data/set/space/base

import com.orchestranetworks.schema.Path;
/**
 * Generated by EBX5 5.4.0 Fix 002 [0907:0001], at  2015/12/21 14:35:06 [EST].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: TheStoreModule, path: /WEB-INF/ebx/schemas/TheStoreDataModule.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Paths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Prefix:  ''.
	// Statistics:
	//		73 path constants.
	//		26 leaf nodes.
	public static final Path _Root = Path.parse("/root");


}
