package com.orchestranetworks.geomatch;

import com.orchestranetworks.schema.Path;
/**
 * Generated by EBX5 5.6.1 Fix A [0985:0003], at  2016/01/27 16:21:04 [EST].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Publication: GeomatchDataModel].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Paths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Prefix:  ''.
	// Statistics:
	//		15 path constants.
	//		5 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Geomatch {
		private static final Path _Geomatch = _Root.add("Geomatch");
		public static Path getPathInSchema()
		{
			return _Geomatch;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _Address = Path.parse("./Address");
	public static final Path _Latitude = Path.parse("./Latitude");
	public static final Path _Longitude = Path.parse("./Longitude");
	public static final Path _IsMatched = Path.parse("./isMatched");
	} 
	// ===============================================

}
